var colors = require('colors');

module.exports = [
	'',
	'-------'.bold.grey,
	'KONTROL'.bold.white,
	'-------'.bold.grey,
	'Send commands to a remote Spotify client',
	'github: https://github.com/carlbardahl/spotify-kontrol-cli',
	'author: <carlbarrdahl@gmail.com>',
	'--------------------------------'.bold.grey,
	'',
	'Usage:'.green.bold,
	'',
	'Play track'.green,
	' kontrol play',
	'',
	'Pause track'.green,
	' kontrol pause',
	'',
	'Play next track'.green,
	' kontrol next',
	'',
	'Play previous track'.green,
	' kontrol prev',
	'',
	'Set player volume'.green,
	' kontrol vol <value>',
	'',
	'Set repeat mode'.green,
	' kontrol repeat <boolean>',
	'',
	'Set shuffle mode'.green,
	' kontrol shuffle <boolean>',

];
